apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato-app
  labels:
    app: zomato
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
      - name: zomato-container
        image: manoharmattepu/zomato:latest  # Replace with your Docker image
        ports:
        - containerPort: 3001  # Replace with the port your app runs on
