apiVersion: v1
kind: Service
metadata:
  name: zomato-service
  labels:
    app: zomato
spec:
  type: NodePort
  ports:
  - port: 3001
    targetPort: 3001  # Replace with the port your app runs on
  selector:
    app: zomato
